# Generated by Django 5.2.16 on 2026-08-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='logo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
