# Generated by Django 5.2.16 on 2026-08-13 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam_management', '0001_initial'),
        ('vendors', '0002_alter_vendorprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='kam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='kam_management.kam'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='profile_picture',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
