# Generated by Django 5.2.16 on 2026-08-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_mobile_verified_user_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer'), ('KAM', 'KAM')], default='CUSTOMER', max_length=20),
        ),
    ]
